### ISSUE TITLE
Might need some parsing each 2 or 3 tags as long tags might do this :

### ISSUE THREAD

**Issue by lostallmymoney** [CrimsonFluff/CrimsonNBTTags#2]
![2022-01-02_04 10 40](https://user-images.githubusercontent.com/6634309/147871416-27eb43f8-78fd-4d4f-852b-0af2f66e9204.png)

**Comment by CrimsonFluff** [comment]
that tooltip is a fabric/vanilla bug - use https://www.curseforge.com/minecraft/mc-mods/tooltipfix
